almost done
Nerubes/review1 pull request #1
Opened 2021-04-04 21:10 UTC by Nerubes

2021-04-10 12:40 UTC, corwinnn requested changes
Добавь гитигнор и убери лишние файлы
Напиши подробное ридми с примерами

2021-04-10 12:40 UTC, corwinnn commented on review1/alphabet.py
> +rus = ' абвгдеёжзийклмнопрстуфхцчшщъьэюя'
этого нет в библиотеке?

2021-04-10 12:40 UTC, corwinnn commented on review1/ceasar.py
> +    for i in string:
i?

2021-04-10 12:40 UTC, corwinnn commented on review1/correct.py
> +    Проверяет строки, чтобы она была исключительно из букв причем одного алфавита
по описанию не ясно, что делает функция

2021-04-10 12:40 UTC, corwinnn commented on review1/hacking_ceasar.py
> +        count[j] += 1
и вот для этого был заведен Counter?

2021-04-10 12:40 UTC, corwinnn commented on review1/main.pyw
> +    if what_cipher.get() == "Ceasar":
Сделай одинаковые кавычки во всех файлах, ' или "

2021-04-10 12:40 UTC, corwinnn commented on review1/vigenere.py
> +def decode(string, seed):
копипаста

2021-04-19 15:23 UTC, corwinnn requested changes

2021-04-19 15:23 UTC, corwinnn commented on review1/alphabet.py
> +rus = ' абвгдеёжзийклмнопрстуфхцчшщъьэюя'
жду ответ

2021-04-19 15:23 UTC, corwinnn commented on review1/bmp.py
> +    for i in string:
плохое название переменной

2021-04-19 15:23 UTC, corwinnn commented on review1/bmp.py
> +        if ord(i) > 127:
магическая константа

2021-04-19 15:23 UTC, corwinnn commented on review1/bmp.py
> +    if img.shape[0] * img.shape[1] < len(string) + 6:
магическая константа

2021-04-19 15:23 UTC, corwinnn commented on review1/bmp.py
> +    if img.shape[0] * img.shape[1] < len(string) + 6:
можно возвращать результат выражения сразу и не писать потом return 2 раза

2021-04-19 15:23 UTC, corwinnn commented on review1/bmp.py
> +        if index >= 8:
магическая константа

2021-04-19 15:23 UTC, corwinnn commented on review1/bmp.py
> +    return res[:-6]
магическая константа

2021-04-19 15:23 UTC, corwinnn commented on review1/bmp.py
> +    for i in storage:
плохое название переменной

2021-04-19 15:23 UTC, corwinnn commented on review1/ceasar.py
> +def decode(string, seed):
копипаста

2021-04-19 15:23 UTC, corwinnn commented on review1/hacking_ceasar.py
> +        count[letter] += 1
нельзя ли передать это сразу в конструктор?

2021-04-19 15:23 UTC, corwinnn commented on review1/main.pyw
> +    if what_cipher.get() == "Ceasar":
не исправлено

2021-04-19 15:23 UTC, corwinnn commented on review1/vernam.py
> +        using_alphabet = alphabet.rus
а если дали какую-то абракадабру, сделай обработчик ошибок

2021-04-19 15:23 UTC, corwinnn commented on review1/vigenere.py
> +def decode(string, seed):
не исправлено

2021-04-20 21:28 UTC, Nerubes commented on review1/alphabet.py
> +rus = ' абвгдеёжзийклмнопрстуфхцчшщъьэюя'
есть, но в библиотеке без пробела строчки, а у меня оно на пробел ориентируется, как на символ, если надо могу переделать

2021-04-21 12:23 UTC, corwinnn commented on review1/alphabet.py
> +rus = ' абвгдеёжзийклмнопрстуфхцчшщъьэюя'
заимпорти строку с алфавитом из библиотеки и добавь к ней пробел

2021-04-21 16:13 UTC, Nerubes commented on review1/alphabet.py
> +rus = ' абвгдеёжзийклмнопрстуфхцчшщъьэюя'
только что выяснил, что не могу найти откуда русский импортить, а если только англ делать оно не очень единообразно выглядеть будет

2021-04-22 20:02 UTC, corwinnn commented on review1/alphabet.py
> +rus = ' абвгдеёжзийклмнопрстуфхцчшщъьэюя'
ок
но все равно сделай 'abc...' + ' '

2021-04-28 05:42 UTC, merged